export const GET_ALL_PROD = 'GET_ALL_PROD';
export const GET_ALL_BRANDS = 'GET_ALL_BRANDS';
export const GET_ALL_CATEGORIES  = 'GET_ALL_CATEGORIES';
export const GET_BEST_SELLERS  = 'GET_BEST_SELLERS';
export const GET_PROD_PRICE_MIN_MAX  = 'GET_PROD_PRICE_MIN_MAX';
export const GET_PROD_COUNT  = 'GET_PROD_COUNT';

export const REQUEST_START  = 'REQUEST_START';
export const REQUEST_SUCCESS  = 'REQUEST_SUCCESS';
export const REQUEST_FAILURE  = 'REQUEST_FAILURE';

export const UPDATE_CART_ITEMS  = 'UPDATE_CART_ITEMS';
export const UPD_ALL_CART_ITEMS  = 'UPD_ALL_CART_ITEMS';
export const GET_CART_ITEMS  = 'GET_CART_ITEMS';
export const REMOVE_ITEM_FROM_CART  = 'REMOVE_ITEM_FROM_CART';
export const REMOVE_ALL_ITEMS_FROM_CART  = 'REMOVE_ALL_ITEMS_FROM_CART';

export const GET_CUSTOMER_DTLS  = 'GET_CUSTOMER_DTLS';
export const SET_CUSTOMER_DTLS  = 'SET_CUSTOMER_DTLS';